### PR TITLE
Fixed for WoW 9.2.5

### PR DESCRIPTION
**Pull request by LenweSaralonde**
* Replaced `SetTexture()` by set `SetColorTexture()`.
* The screen has been divided into pixel rows (one frame per row) to avoid reaching the children limit per frame.
* Added missing libraries.
* Fixed LUA error in `drawrect()` function (bounds).

### CODE REVIEW

**Review by cfoust — APPROVED** [review]
Holy crap, thanks for the contribution! I never expected anyone to think about this again lol

**Comment by cfoust** [comment]
Also feel free to add your name to the author list in the `.toc`, fixing this made my day! I used to publish this on Curseforge back in the day but it's probably not there anymore; if you'd like to publish it somewhere, go ahead. Admittedly the user experience could be better for importing ROMs. If this is working again maybe I could come back and look at that. Let me know.

**Comment by LenweSaralonde** [comment]
I was told about this project by Ovokalia from the Total RP Discord and Meorawr figured out the problem of the frame amount limit so I made this PR to make it run and try it.

It's a fun project but don't think I'll work more on it since there is still a lot of work to be done (especially on optimization because it's still very slow, even on a high specs PC) to make it actually fun to use.

> Admittedly the user experience could be better for importing ROMs. 

I had the same issue with my music add-on [Musician](https://github.com/LenweSaralonde/Musician) and [MusicianList](https://github.com/LenweSaralonde/MusicianList) to allow users to load MIDI files in WoW. 

An easy way to address this is to make a small local web app in a `.html` file attached in the add-on folder to convert binary files into text. The user just has to drag and drop the binary file to the web page then it's encoded into a base64 string that can be copy-pasted into WoW as plain text (the same way as Weak Aura does). The base64 string is then decoded in game back to binary. You can also host [a online version](https://musician.lenwe.io/import/) of the web app so it can double as a home page for the project.

To make it even more convenient to the user, you can also store the binary data in game inside a SavedVariables table and use [LibDeflate](https://github.com/safeteeWow/LibDeflate/) to compress/decompress it so it uses less RAM.

**Comment by LenweSaralonde** [comment]
The only other thing I tried is to (sort of) get sound off the emulator using using Musician's API. The result is... 
[interesting](https://youtu.be/sDaCXLQnaZA). Maybe adding pre-recorded samples of square/pulse/triangle wave notes with a better understanding of the implementation could lead to something more convincing.
The branch with the test commit is here : https://github.com/LenweSaralonde/gnomeboy/commit/897c76646cc62cfffc525c94d260d2d3aa85d70f

**Comment by cfoust** [comment]
😱 Holy crap, this made my day! The video of audio working is hilarious, honestly I think it adds to the effect. So cool to see this in action again.

Re: the small site for formatting the ROMs correctly is definitely the best option. I could throw that together.

Admittedly I was not very good at programming in 2013 -- if you think this is interesting, I could go in and take a stab at optimizing the code. Since this was written there have definitely been some innovations in this (think asm.js, Emscripten, etc.)

Let me know what features you think would be neat. This was really just a tech demo back in the day; I wanted to see if it was possible.

**Comment by milkcanworld** [comment]
This addon is awesome! I found that by commenting out `self:RegisterForDrag(nil)` calls in `skins/classic.lua` and `skins/screen.lua` as well as changing line 210 in `lib/skinManager.lua` to `screen.pixels[i][j] = screen.rows[i]:CreateTexture(nil,"ARTWORK");`, I could get the emulator to load and play games successfully on the latest Classic Era. I have never touched WoW addon code before this in my life, and don't actually know any of the API; these are not the right fixes, but the addon works!

image
_working on interface version 11505, the latest Classic Era version!_

The Musician support is _amazing_ judging by that video. I would love to see this emulator optimized at some point! Exporting the saves would be pretty neat as well, I'd go back and forth between my real Game Boys and this. :)

**Comment by cfoust** [comment]
I’m once again shocked that someone found this addon and took the time to tinker with it! I’m so impressed you got it working, I wasn’t sure it would ever work again. I currently don’t have a way to test these changes but I’ll push them to the main branch anyway. Thank you so much! Would love to see a video of this in action :)

**Pull request merged**
